// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_Djud6GBl6e-mSt-3VyrZZuRSuQBN9s',
    appId: '1:270384841266:web:d333083cdeeff0befbf22b',
    messagingSenderId: '270384841266',
    projectId: 'app-agenda-55e88',
    authDomain: 'app-agenda-55e88.firebaseapp.com',
    storageBucket: 'app-agenda-55e88.appspot.com',
    measurementId: 'G-CMQBS4JNND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk37Cb84_UhSvjkSbrIJuE8vukHw5S0jU',
    appId: '1:270384841266:android:6c5b317795431510fbf22b',
    messagingSenderId: '270384841266',
    projectId: 'app-agenda-55e88',
    storageBucket: 'app-agenda-55e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHRKl0FU56HjGtvuxjr0mWsFx2CsgyaSI',
    appId: '1:270384841266:ios:80f73b8c78566b4efbf22b',
    messagingSenderId: '270384841266',
    projectId: 'app-agenda-55e88',
    storageBucket: 'app-agenda-55e88.appspot.com',
    iosBundleId: 'com.example.appAgenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHRKl0FU56HjGtvuxjr0mWsFx2CsgyaSI',
    appId: '1:270384841266:ios:80f73b8c78566b4efbf22b',
    messagingSenderId: '270384841266',
    projectId: 'app-agenda-55e88',
    storageBucket: 'app-agenda-55e88.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHRKl0FU56HjGtvuxjr0mWsFx2CsgyaSI',
    appId: '1:270384841266:ios:80f73b8c78566b4efbf22b',
    messagingSenderId: '270384841266',
    projectId: 'app-agenda-55e88',
    storageBucket: 'app-agenda-55e88.appspot.com',
  );
}
